// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Automation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Orders screen")]
    public partial class OrdersScreenFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Everlight.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Orders screen", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add order on Orders screen")]
        [NUnit.Framework.TestCaseAttribute("4567", "Test", "Auto", "8742", "Lumus (LUM)", "Ingleburn", "CT (CT)", "06/08/2021 11:49 AM", null)]
        public virtual void AddOrderOnOrdersScreen(string mRN, string firstName, string lastName, string accessionNumber, string organisation, string siteId, string modality, string studyDateTime, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("MRN", mRN);
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("AccessionNumber", accessionNumber);
            argumentsOfScenario.Add("Organisation", organisation);
            argumentsOfScenario.Add("SiteId", siteId);
            argumentsOfScenario.Add("Modality", modality);
            argumentsOfScenario.Add("StudyDateTime", studyDateTime);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add order on Orders screen", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
 testRunner.Given("the user is on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "MRN",
                            "FirstName",
                            "LastName",
                            "AccessionNumber",
                            "Organisation",
                            "SiteId",
                            "Modality",
                            "StudyDateTime"});
                table1.AddRow(new string[] {
                            string.Format("{0}", mRN),
                            string.Format("{0}", firstName),
                            string.Format("{0}", lastName),
                            string.Format("{0}", accessionNumber),
                            string.Format("{0}", organisation),
                            string.Format("{0}", siteId),
                            string.Format("{0}", modality),
                            string.Format("{0}", studyDateTime)});
#line 5
 testRunner.When("the user adds a new order with following data", ((string)(null)), table1, "When ");
#line hidden
#line 8
 testRunner.Then(string.Format("the order should be added with accession number \'{0}\'", accessionNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
 testRunner.And("delete the order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Order not added when data is missing")]
        [NUnit.Framework.TestCaseAttribute("", "Test", "Auto", "8742", "Lumus (LUM)", "Ingleburn", "CT (CT)", "06/08/2021 11:49 AM", "MRN is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "", "Auto", "8742", "Lumus (LUM)", "Ingleburn", "CT (CT)", "06/08/2021 11:49 AM", "First Name is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "Test", "", "8742", "Lumus (LUM)", "Ingleburn", "CT (CT)", "06/08/2021 11:49 AM", "Last Name is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "Test", "Auto", "", "Lumus (LUM)", "Ingleburn", "CT (CT)", "06/08/2021 11:49 AM", "Accession Number is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "Test", "Auto", "8742", "", "Ingleburn", "CT (CT)", "06/08/2021 11:49 AM", "Organisation is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "Test", "Auto", "8742", "Lumus (LUM)", "", "CT (CT)", "06/08/2021 11:49 AM", "Site is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "Test", "Auto", "8742", "Lumus (LUM)", "Ingleburn", "", "06/08/2021 11:49 AM", "Modality: The Modality field is required.", null)]
        [NUnit.Framework.TestCaseAttribute("1234", "Test", "Auto", "8742", "Lumus (LUM)", "Ingleburn", "CT (CT)", "", "Study DateTime is required.", null)]
        public virtual void OrderNotAddedWhenDataIsMissing(string mRN, string firstName, string lastName, string accessionNumber, string organisation, string siteId, string modality, string studyDateTime, string error, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("MRN", mRN);
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("AccessionNumber", accessionNumber);
            argumentsOfScenario.Add("Organisation", organisation);
            argumentsOfScenario.Add("SiteId", siteId);
            argumentsOfScenario.Add("Modality", modality);
            argumentsOfScenario.Add("StudyDateTime", studyDateTime);
            argumentsOfScenario.Add("error", error);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Order not added when data is missing", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
 testRunner.Given("the user is on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "MRN",
                            "FirstName",
                            "LastName",
                            "AccessionNumber",
                            "Organisation",
                            "SiteId",
                            "Modality",
                            "StudyDateTime"});
                table2.AddRow(new string[] {
                            string.Format("{0}", mRN),
                            string.Format("{0}", firstName),
                            string.Format("{0}", lastName),
                            string.Format("{0}", accessionNumber),
                            string.Format("{0}", organisation),
                            string.Format("{0}", siteId),
                            string.Format("{0}", modality),
                            string.Format("{0}", studyDateTime)});
#line 17
 testRunner.When("the user tries to add a new order with following data", ((string)(null)), table2, "When ");
#line hidden
#line 20
 testRunner.Then(string.Format("the order should not be added with error \'{0}\'", error), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
